### ISSUE TITLE
Reading a fits file returns empty(?) dask array

### ISSUE THREAD

**Issue by ronpandolfi** [intake/intake-astro#7]
Here I'm trying to open a fits file with astropy.io.fits:
```
In[42]: f=fits.open('20161214_00034.fits')
In[43]: f[1].data.shape
Out[43]: (5776,)
```
This is correct. However when reading with FITSArraySource, I get some warnings and the resulting dask array is empty
```
In[44]: f=FITSArraySource('20161214_00034.fits')
In[45]: f.shape
WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATE-REF to '1858-11-17' from MJD-REF'. [astropy.wcs.wcs]
In[46]: f.to_dask().shape
Out[46]: ()
In[47]: 
```

**Comment by martindurant** [comment]
Is there any chance you can share the file? You might want to set some pdb breakpoints to try to see what's going on in the code - there isn't that much of it.

**Comment by martindurant** [comment]
After a moment reminding myself of how this package works, the most likely problem is not specifying the extension number. intake-astro does not guess the first data extension (in the case you have a default metadata-only zeroth extension)

**Comment by ronpandolfi** [comment]
Specifying the extension gives the following:
```
In[93]: FITSArraySource('20161214_00034.fits',ext=1).to_dask().shape
Traceback (most recent call last):
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-93-5a4805d6e1ad>", line 1, in <module>
    FITSArraySource('20161214_00034.fits',ext=1).to_dask().shape
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\intake_astro\array.py", line 101, in to_dask
    self._get_schema()
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\intake_astro\array.py", line 58, in _get_schema
    self.files[0], self.ext)
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\intake_astro\array.py", line 154, in _get_header
    dtype = fits.hdu.image.BITPIX2DTYPE[hdu._bitpix]
AttributeError: 'BinTableHDU' object has no attribute '_bitpix'
```
I'll probe things a bit with pdb. There's a possibility that its not exactly fits spec; its written out by some labview code, but it works with Astropy's reader. What's a good private channel I can use to send you the data file?

**Comment by martindurant** [comment]
Ah, so you have a table, not an array. You need the `FITSTableSource` source ('fits_table').

**Comment by ronpandolfi** [comment]
Here is the result as a table:
```
In[103]: FITSTableSource('20190915_01322.fits',ext=1).to_dask().shape
Traceback (most recent call last):
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-103-afb3534823b8>", line 1, in <module>
    FITSTableSource('20190915_01322.fits',ext=1).to_dask().shape
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\intake_astro\table.py", line 95, in to_dask
    self._get_schema()
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\intake_astro\table.py", line 75, in _get_schema
    header, dtype, shape = _get_fits_header(part, self.ext)
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\intake_astro\table.py", line 156, in _get_fits_header
    return dict(hdu.header.items()), _dtypes(hdu), (
  File "C:\Users\LBL\PycharmProjects\merged-repo\venv\lib\site-packages\intake_astro\table.py", line 163, in _dtypes
    for i, (field, d) in enumerate(dt):
ValueError: too many values to unpack (expected 2)
```

**Comment by martindurant** [comment]
Do you mind showing the `.info()` of the file?

**Comment by ronpandolfi** [comment]
Here's the `.info()` from Astropy:
```
In[107]: f.info()
Filename: 20161214_00034.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     200   ()      
  1  data          1 BinTableHDU     36   5776R x 5C   [1D, 1D, 1D, 1D, 241944J]
```
Looks like there's a few non-image records. The last one is images of shape (408, 593).

**Comment by martindurant** [comment]
I guess you could debug the line `for i, (field, d) in enumerate(dt):` to see what `dt` (or `list(dt)`) actually is.

Certainly, the data is neither table nor array, but uses "heap" for the nested structure, so it won't fit well with randomly accessing blocks from the data and loading piecewise, but you should still be able to read the whole extension in one go.
